
# Initial learning rate.
initial_learning_rate: 0.0001

# The batch size to use.
batch_size: 4

# Directory where to write event logs and checkpoint.
train_dir: 'ckpt/train'

# If specified, restore this pretrained model before beginning any training.
pretrained_model_checkpoint_path: ''

# The number of hidden units in the recurrent model
hidden_units: 256

# The number of consecutive examples to be used in the recurrent model.
seq_length: 2

# Which model is going to be used: audio, video, or both.
model: 'both'

# The tfrecords directory.
dataset_dir: 'path_to_tfrecords'

